name: advertising_info
description: A Flutter plugin for fetching Advertising info from Android and iOS
version: 0.2.1
homepage: https://github.com/liahoo/AdvertisingInfo

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fascode.advertising_info
        pluginClass: AdvertisingInfoPlugin
      ios:
        pluginClass: AdvertisingInfoPlugin
